version: "3.3"

services:

  apache:

    container_name: apache_sserver
    image: httpd
    networks:
      nt01:
        ipv4_address: 192.0.0.10
    ports:
      - 90:90
    volumes:
      - htdocs:/usr/local/apache2/htdocs

  bind9:
    container_name: bind9_server
    image: internetsystemsconsortium/bind9:9.16

    networks:
      nt01:
        ipv4_address: 192.0.0.254
    ports:
      - 56:56
    volumes:
      - bind:/etc/bind
  cliente:
    container_name: apache_cliente
    image: kasmweb/desktop-deluxe:1.9.0-rolling

    networks:
      nt01:
        ipv4_address: 192.0.0.2
    ports:
      - 6901:6901
    dns:
      - 192.0.0.254 
    environment:
      - VNC_PW= abc123.

volumes:
  bind:
    external: true
  htdocs:
    external: true
    
networks:
  nt01:
    ipam:
      config:
        - subnet: 192.0.0.0/24